### ISSUE TITLE
Issues list

### ISSUE THREAD

**Issue by prokopsimek** [no-need-to-be-anonymous/express-starter-buttercms#1]
**Code review:**
- [x] prod shouldn't be run in nodemon but as a plain node process (https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/package.json#L3)
- [x] error handling is set just for an invalid token, and there is unhandled any other error (https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/index.js#L270-L271)
- [ ] These sections are same (convert to function)- https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/index.js#L62-L94 and https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/index.js#L240-L273
- [ ] Does the `/landing-page/<slug>` work for landing page? I don't see any route for that. (Original requirement in `# Index View` => `- [ ] Secondary route is set to either /<slug> or /landing-page/<slug> to enable previewing in ButterCMS.com
iframe panel, as iframe panel does not currently explicitly allow previewing of index.`)

- [ ] pls lint https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/views/index.ejs
- [ ] also pls lint https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/views/layout.ejs#L40-L43
- [ ] can you add some EJS plugin for eslint?
- [ ] this https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/views/404.ejs#L1-L25 can also be used as a layout
- [ ] all ejs files seems not formatted at all
- [x] 1) never sort on frontend but backend (API query parameter), 2) blog posts are already ordered by date https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/views/sections/blog-section.ejs#L21-L22
- [x] add alt description for images https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/views/sections/hero.ejs#L26 I think that these descriptions are also returned in the API
- [x] you probably forgot to remove static HTML of testimonials https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/views/sections/testimonials.ejs#L25-L66
- [x] is the vercel.json necessary? https://github.com/no-need-to-be-anonymous/express-starter-buttercms/blob/main/vercel.json

Visual review:
- [x] active section is not highlighted in navigation while scrolling on the homepage
- [x] favicon is missing
- [x] "Customize this page" doesn't render HTML elements correctly (I can see plaintext HTML there)
- [x] https://express-starter-buttercms-dxheroes.vercel.app/asdf should render 404 page and not the landing page
- [x] I've got timeout for non-existing article detail URL https://express-starter-buttercms-dxheroes.vercel.app/blog/aaaaadefrjhgsreiughresigbesro (should be 404 page)

I haven't tried yet case if no API token set or invalid token set. I will try later.

**Comment by no-need-to-be-anonymous** [comment]
Fixed with commit a6bca487c975ea3cb25510f764f6e03229f0eaaa
